name: docs

on:
  push:
    branches:
      - main
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      - uses: baptiste0928/cargo-install@v2
        with:
          crate: mdbook-admonish
          version: "1.9.0"

      - uses: baptiste0928/cargo-install@v2
        with:
          crate: mdbook-svgbob2
          version: "0.3.0"

      - uses: baptiste0928/cargo-install@v2
        with:
          crate: mdbook-linkcheck
          version: "0.7.7"

      - name: Build with mdbook
        run: mdbook build book

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/book/html
          force_orphan: true
